//
//  Account.swift
//  ChurnApp
//
//  A bank account opened (or being considered) for a churning bonus. This is
//  the centre of the schema: everything else hangs off it.
//
//  See `Person.swift` for why these classes are hand-written rather than
//  generated by Xcode.
//

import CoreData
import Foundation

@objc(Account)
public class Account: NSManagedObject {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Account> {
        NSFetchRequest<Account>(entityName: "Account")
    }

    // MARK: - Attributes

    @NSManaged public var id: UUID
    @NSManaged public var bankName: String
    /// Raw value of `AccountType`. Prefer `accountTypeValue`.
    @NSManaged public var accountType: String
    @NSManaged public var openingDate: Date
    /// The model enforces a minimum of 0, i.e. it rejects negative bonuses.
    /// Core Data truncates fractional `minValueString` bounds on Decimal
    /// attributes, so "must be greater than zero" cannot be expressed here —
    /// entry forms are responsible for rejecting a $0 bonus.
    ///
    /// Money is always `NSDecimalNumber` in the store — Core Data cannot back a
    /// `Decimal` struct with `@NSManaged`. Use `bonusAmountDecimal` for
    /// arithmetic; never convert money through `Double`.
    @NSManaged public var bonusAmount: NSDecimalNumber
    /// Raw value of `BonusStructure`. Prefer `bonusStructureValue`.
    @NSManaged public var bonusStructure: String
    /// Free text, straight from the offer's fine print.
    @NSManaged public var bonusRequirements: String
    /// Balance needed to avoid a monthly fee. Optional because plenty of
    /// accounts have none, which is meaningfully different from "$0 required".
    @NSManaged public var minimumBalance: NSDecimalNumber?
    @NSManaged public var expectedBonusDate: Date?
    @NSManaged public var actualBonusDate: Date?
    /// Raw value of `AccountStatus`. Prefer `accountStatusValue`.
    @NSManaged public var accountStatus: String
    @NSManaged public var closedDate: Date?
    /// How long after this bonus the bank blocks another one (12 or 24 months).
    @NSManaged public var eligibilityMonths: Int16
    @NSManaged public var accountNumberLast4: String?
    @NSManaged public var notes: String?
    /// Soft-delete flag. Named `isArchived` rather than `isDeleted` because
    /// `NSManagedObject` already defines `isDeleted` and shadowing it breaks
    /// Core Data's own change tracking.
    @NSManaged public var isArchived: Bool
    @NSManaged public var createdAt: Date
    @NSManaged public var updatedAt: Date

    // MARK: - Relationships

    @NSManaged public var person: Person?
    @NSManaged public var reminders: NSSet?
    @NSManaged public var directDeposits: NSSet?
    /// The offer this account was opened from, if the user tracked one.
    /// Nullify both ways: offers are reference data that outlive accounts, and
    /// deleting an account must never delete the offer it came from.
    @NSManaged public var offer: Offer?
}

// MARK: - Typed accessors

extension Account {

    /// `bonusAmount` as a Swift `Decimal`.
    var bonusAmountDecimal: Decimal {
        get { bonusAmount.decimalValue }
        set { bonusAmount = NSDecimalNumber(decimal: newValue) }
    }

    var accountTypeValue: AccountType {
        get { AccountType(rawValue: accountType) ?? .checking }
        set { accountType = newValue.rawValue }
    }

    var bonusStructureValue: BonusStructure {
        get { BonusStructure(rawValue: bonusStructure) ?? .lumpSum }
        set { bonusStructure = newValue.rawValue }
    }

    var accountStatusValue: AccountStatus {
        get { AccountStatus(rawValue: accountStatus) ?? .prospecting }
        set { accountStatus = newValue.rawValue }
    }

    /// True once the bonus has actually landed. The single source of truth for
    /// "earned" money — `bonusAmount` alone is only a projection.
    var hasBonusPosted: Bool { actualBonusDate != nil }

    var remindersArray: [Reminder] {
        (reminders as? Set<Reminder> ?? []).sorted { $0.dueDate < $1.dueDate }
    }

    var directDepositsArray: [DirectDeposit] {
        (directDeposits as? Set<DirectDeposit> ?? []).sorted { $0.scheduledDate < $1.scheduledDate }
    }
}

// MARK: - Generated relationship accessors

extension Account {

    @objc(addRemindersObject:)
    @NSManaged public func addToReminders(_ value: Reminder)

    @objc(removeRemindersObject:)
    @NSManaged public func removeFromReminders(_ value: Reminder)

    @objc(addReminders:)
    @NSManaged public func addToReminders(_ values: NSSet)

    @objc(removeReminders:)
    @NSManaged public func removeFromReminders(_ values: NSSet)

    @objc(addDirectDepositsObject:)
    @NSManaged public func addToDirectDeposits(_ value: DirectDeposit)

    @objc(removeDirectDepositsObject:)
    @NSManaged public func removeFromDirectDeposits(_ value: DirectDeposit)

    @objc(addDirectDeposits:)
    @NSManaged public func addToDirectDeposits(_ values: NSSet)

    @objc(removeDirectDeposits:)
    @NSManaged public func removeFromDirectDeposits(_ values: NSSet)
}

extension Account: Identifiable {}
