//
//  Bank.swift
//  ChurnApp
//
//  A bank as a real row (Chase, Wells Fargo, SoFi…) rather than a free-text
//  string. Added in round 2 so "am I eligible for this offer given my last
//  bonus at this bank" is a relationship lookup instead of fuzzy string
//  matching.
//
//  IMPORTANT — this is *additive*. `Account.bankName` and `Offer.bankName`
//  still exist and are still what every round-1 view renders. A `Bank` row is
//  an optional, stronger link alongside them: the Bank picker finds-or-creates
//  a row by case-insensitive name and keeps `bankName` in sync. Nothing
//  migrates, and code must keep working when `bank` is nil.
//
//  See `Person.swift` for why these classes are hand-written rather than
//  generated by Xcode.
//

import CoreData
import Foundation

@objc(Bank)
public class Bank: NSManagedObject {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<Bank> {
        NSFetchRequest<Bank>(entityName: "Bank")
    }

    // MARK: - Attributes

    @NSManaged public var id: UUID
    /// Display name as the user typed it the first time this bank was created.
    /// Matching elsewhere is case-insensitive; this preserves their casing.
    @NSManaged public var name: String
    @NSManaged public var createdAt: Date

    // MARK: - Relationships

    /// Nullify both ways: a bank is reference data that outlives any one
    /// account. Deleting a bank must unlink its accounts, never delete them
    /// (they still carry `bankName`, so no data is lost).
    @NSManaged public var accounts: NSSet?
    /// Nullify for the same reason as `accounts`.
    @NSManaged public var offers: NSSet?
}

// MARK: - Typed accessors

extension Bank {

    /// Accounts as a stable, sorted array — `NSSet` has no order, and SwiftUI
    /// `ForEach` needs one.
    var accountsArray: [Account] {
        (accounts as? Set<Account> ?? []).sorted { $0.openingDate > $1.openingDate }
    }

    var offersArray: [Offer] {
        (offers as? Set<Offer> ?? []).sorted { $0.createdAt > $1.createdAt }
    }
}

// MARK: - Generated relationship accessors

extension Bank {

    @objc(addAccountsObject:)
    @NSManaged public func addToAccounts(_ value: Account)

    @objc(removeAccountsObject:)
    @NSManaged public func removeFromAccounts(_ value: Account)

    @objc(addAccounts:)
    @NSManaged public func addToAccounts(_ values: NSSet)

    @objc(removeAccounts:)
    @NSManaged public func removeFromAccounts(_ values: NSSet)

    @objc(addOffersObject:)
    @NSManaged public func addToOffers(_ value: Offer)

    @objc(removeOffersObject:)
    @NSManaged public func removeFromOffers(_ value: Offer)

    @objc(addOffers:)
    @NSManaged public func addToOffers(_ values: NSSet)

    @objc(removeOffers:)
    @NSManaged public func removeFromOffers(_ values: NSSet)
}

extension Bank: Identifiable {}
